-- Up
-- Migration: 010_content_cascade
-- Description: Creates tables for the Multi-Agent Content Cascade (v2 PoC)

-- 1. Monthly Themes (Strategic)
CREATE TABLE monthly_themes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    theme VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(year, month)
);

-- 2. Weekly Topics (Tactical)
CREATE TABLE weekly_topics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    monthly_theme_id UUID REFERENCES monthly_themes(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    week_number INTEGER NOT NULL,
    topic VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(year, week_number)
);

-- 3. Content Queue (Operational/Briefings)
CREATE TABLE content_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    weekly_topic_id UUID REFERENCES weekly_topics(id) ON DELETE SET NULL,
    post_date DATE NOT NULL,
    platform VARCHAR(50) NOT NULL,
    format VARCHAR(50) NOT NULL, -- e.g., 'carousel_cover', 'fixed_image'
    briefing_json JSONB,         -- Generated briefing/JSON output from DailyBriefingAgent
    visual_prompt JSONB,         -- JSON used for Visual Designer prompt
    image_url TEXT,              -- S3/Supabase Storage URL
    caption TEXT,                -- Generated by Copywriter
    status VARCHAR(50) DEFAULT 'draft' NOT NULL, -- 'draft', 'pending_approval', 'approved', 'published'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(post_date, platform)
);

-- Function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_metrics_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for content_queue
CREATE TRIGGER trigger_update_content_queue_updated_at
BEFORE UPDATE ON content_queue
FOR EACH ROW
EXECUTE FUNCTION update_metrics_updated_at();

-- RLS Policies (Assuming service role usage mostly, but good practice to enable)
ALTER TABLE monthly_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to monthly_themes" ON monthly_themes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access to weekly_topics" ON weekly_topics FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access to content_queue" ON content_queue FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Down
-- DROP TRIGGER IF EXISTS trigger_update_content_queue_updated_at ON content_queue;
-- DROP TABLE IF EXISTS content_queue;
-- DROP TABLE IF EXISTS weekly_topics;
-- DROP TABLE IF EXISTS monthly_themes;
